FROM alpine:latest

# Copy the run_ollama.sh script into the container
COPY start_service.sh /app/start_service.sh

# Ensure the script is executable
RUN chmod +x /app/start_service.sh

# Install wget and docker-client
RUN apk add --no-cache wget docker-cli

# Set the entrypoint to run the script
ENTRYPOINT ["/app/start_service.sh"]
