services:
  ollama-container:
    build:
      context: .
      dockerfile: Dockerfile.ollama
    volumes:
      - ./data/ollama:/root/.ollama
    ports:
      - 11434:11434
    networks:
      - my_network
    environment:
      OLLAMA_HOST: ollama-container
      OLLAMA_PORT: 11434
      OLLAMA_NUM_PARALLEL: 14

  day2-rag-llm:
    build:
      context: .
      dockerfile: Dockerfile.main
    depends_on:
      - ollama-container
    ports:
      - 7860:7860
    networks:
    - my_network
    environment:
      OLLAMA_HOST: ollama-container
      OLLAMA_PORT: 11434


networks:
  my_network:
    external: true
